#ifndef ACTION_TYPEDEF_H
#define ACTION_TYPEDEF_H

/**
 * @file action_typedef.h
 * @brief Defines macros and enums Actions used by the C API.
 */

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

#include <stdint.h>

#define INSTRUMENT_TYPE_INDEX_OFFSET 24u
#define INSTRUMENT_TYPE_INDEX_MASK 0xFF000000u
#define INSTRUMENT_ACTION_CODE_OFFSET 0u
#define INSTRUMENT_ACTION_CODE_MASK 0x00FFFFFFu

/**
 * @brief Macro for defining creating an Action enumeration for each Instrument type
 */
#define INSTRUMENT_ACTION(instrumentType, actionCode)                                                                  \
    (uint32_t)(((((uint32_t)(instrumentType)) << (INSTRUMENT_TYPE_INDEX_OFFSET)) & (INSTRUMENT_TYPE_INDEX_MASK)) |     \
               ((((uint32_t)(actionCode)) << (INSTRUMENT_ACTION_CODE_OFFSET)) & (INSTRUMENT_ACTION_CODE_MASK)))

/**
 * @brief Macro for extracting the Instrument type from an Action enumeration
 */
#define INSTRUMENT_TYPE(instrumentAction)                                                                              \
    (uint32_t)(((instrumentAction) & (INSTRUMENT_TYPE_INDEX_MASK)) >> (INSTRUMENT_TYPE_INDEX_OFFSET))

/**
 * @brief Macro for extracting the Action code from an Action enumeration
 */
#define INSTRUMENT_ACTION_CODE(instrumentAction) (uint32_t)((instrumentAction) & (INSTRUMENT_ACTION_CODE_MASK))

typedef void* InstrumentInputType;

typedef void* InstrumentOutputType;

typedef enum {
    INSTRUMENT_BLUETOOTH = 0,
    INSTRUMENT_CELLULAR,
    INSTRUMENT_GPS,
    INSTRUMENT_WIFI,
    INSTRUMENT_COMMS,
    INSTRUMENT_SIMULATION,
} InstrumentType;

typedef enum {
    BLUETOOTH_ACTION_GET_ADAPTER_INFO = 0,
    BLUETOOTH_ACTION_DISCOVER_DEVICES,
    BLUETOOTH_ACTION_DISCOVER_BRATISLAVA_LINKS,
    BLUETOOTH_ACTION_IS_UP,
    BLUETOOTH_ACTION_TURN_ON,
    BLUETOOTH_ACTION_TURN_OFF,
    BLUETOOTH_ACTION_SCAN_ON,
    BLUETOOTH_ACTION_SCAN_OFF,
} BluetoothActions;

typedef enum {
    CELLULAR_ACTION_GEOLOCATE = 0,
} CellularActions;

typedef enum {
    GPS_ACTION_GET_POSITION = 0,
} GpsActions;

typedef enum {
    WIFI_ACTION_GET_MY_DEVICE = 0,
    WIFI_ACTION_DISCOVER_DEVICES,
    WIFI_ACTION_DISCOVER_BRATISLAVA_LINKS,
    WIFI_ACTION_IS_UP,
    WIFI_ACTION_TURN_ON,
    WIFI_ACTION_TURN_OFF,
    WIFI_ACTION_SCAN_ON,
    WIFI_ACTION_SCAN_OFF,
} WifiActions;

typedef enum {
    COMMS_ACTION_DISCOVER_BRATISLAVA_LINKS = 0,
} CommsActions;

typedef enum {
    SIMULATION_ACTION_GET_STATE = 0,
} SimulationActions;

typedef enum {
    INSTRUMENT_API_SUCCESS = 0,
    INSTRUMENT_API_ERROR,
    INSTRUMENT_API_NOT_SUPPORTED,
} instrument_api_status_t;

typedef enum {
    INSTRUMENT_BLUETOOTH_GET_ADAPTER_INFO = INSTRUMENT_ACTION(INSTRUMENT_BLUETOOTH, BLUETOOTH_ACTION_GET_ADAPTER_INFO),
    INSTRUMENT_BLUETOOTH_DISCOVER_DEVICES = INSTRUMENT_ACTION(INSTRUMENT_BLUETOOTH, BLUETOOTH_ACTION_DISCOVER_DEVICES),
    INSTRUMENT_BLUETOOTH_DISCOVER_BRATISLAVA_LINKS =
        INSTRUMENT_ACTION(INSTRUMENT_BLUETOOTH, BLUETOOTH_ACTION_DISCOVER_BRATISLAVA_LINKS),
    INSTRUMENT_BLUETOOTH_IS_UP       = INSTRUMENT_ACTION(INSTRUMENT_BLUETOOTH, BLUETOOTH_ACTION_IS_UP),
    INSTRUMENT_BLUETOOTH_TURN_ON     = INSTRUMENT_ACTION(INSTRUMENT_BLUETOOTH, BLUETOOTH_ACTION_TURN_ON),
    INSTRUMENT_BLUETOOTH_TURN_OFF    = INSTRUMENT_ACTION(INSTRUMENT_BLUETOOTH, BLUETOOTH_ACTION_TURN_OFF),
    INSTRUMENT_BLUETOOTH_SCAN_ON     = INSTRUMENT_ACTION(INSTRUMENT_BLUETOOTH, BLUETOOTH_ACTION_SCAN_ON),
    INSTRUMENT_BLUETOOTH_SCAN_OFF    = INSTRUMENT_ACTION(INSTRUMENT_BLUETOOTH, BLUETOOTH_ACTION_SCAN_OFF),
    INSTRUMENT_CELLULAR_GEOLOCATE    = INSTRUMENT_ACTION(INSTRUMENT_CELLULAR, CELLULAR_ACTION_GEOLOCATE),
    INSTRUMENT_GPS_GET_POSITION      = INSTRUMENT_ACTION(INSTRUMENT_GPS, GPS_ACTION_GET_POSITION),
    INSTRUMENT_WIFI_GET_MY_DEVICE    = INSTRUMENT_ACTION(INSTRUMENT_WIFI, WIFI_ACTION_GET_MY_DEVICE),
    INSTRUMENT_WIFI_DISCOVER_DEVICES = INSTRUMENT_ACTION(INSTRUMENT_WIFI, WIFI_ACTION_DISCOVER_DEVICES),
    INSTRUMENT_WIFI_DISCOVER_BRATISLAVA_LINKS =
        INSTRUMENT_ACTION(INSTRUMENT_WIFI, WIFI_ACTION_DISCOVER_BRATISLAVA_LINKS),
    INSTRUMENT_WIFI_IS_UP    = INSTRUMENT_ACTION(INSTRUMENT_WIFI, WIFI_ACTION_IS_UP),
    INSTRUMENT_WIFI_TURN_ON  = INSTRUMENT_ACTION(INSTRUMENT_WIFI, WIFI_ACTION_TURN_ON),
    INSTRUMENT_WIFI_TURN_OFF = INSTRUMENT_ACTION(INSTRUMENT_WIFI, WIFI_ACTION_TURN_OFF),
    INSTRUMENT_WIFI_SCAN_ON  = INSTRUMENT_ACTION(INSTRUMENT_WIFI, WIFI_ACTION_SCAN_ON),
    INSTRUMENT_WIFI_SCAN_OFF = INSTRUMENT_ACTION(INSTRUMENT_WIFI, WIFI_ACTION_SCAN_OFF),
    INSTRUMENT_COMMS_DISCOVER_BRATISLAVA_LINKS =
        INSTRUMENT_ACTION(INSTRUMENT_COMMS, COMMS_ACTION_DISCOVER_BRATISLAVA_LINKS),
    INSTRUMENT_SIMULATION_GET_STATE = INSTRUMENT_ACTION(INSTRUMENT_SIMULATION, SIMULATION_ACTION_GET_STATE),
} InstrumentActions;

#ifdef __cplusplus
}
#endif // __cplusplus

#endif // ACTION_TYPEDEF_H
